apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wkd
  labels:
    app.kubernetes.io/name: wkd
roleRef:
  kind: ClusterRole
  name: wkd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: wkd
