apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wkd
  labels:
    app.kubernetes.io/name: wkd
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
