kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    app.kubernetes.io/name: wkd
    app.kubernetes.io/part-of: wkd
  name: wkd
roleRef:
  kind: ClusterRole
  name: wkd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: wkd
