apiVersion: apps/v1
kind: Deployment
metadata:
  name: wkd
  labels:
    app: wkd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wkd
  template:
    metadata:
      labels:
        app: wkd
    spec:
      initContainers:
        - name: generator
          image: "drgrove/wkd:v1.3.0"
          env:
            - name: HU_FOLDER
              value: /data/hu/
          volumeMounts:
            - name: keys
              mountPath: /data/keys/
            - name: wkd
              mountPath: /data/hu/
          args:
            - "--use-folder"
            - "/data/keys/"
      containers:
        - name: nginx
          image: "nginx:1.19.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: wkd
              mountPath: /usr/share/nginx/html/.well-known/openpgpkey/hu/
            - name: nginx
              mountPath: /etc/nginx/conf.d/
      volumes:
      - name: wkd
        emptyDir: {}
      - name: keys
        configMap:
          name: keys
      - name: nginx
        configMap:
          name: nginx
