apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf: |-
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      root /usr/share/nginx/html;

      location / {
        index  index.html index.htm;
      }

      location /.well-known/openpgpkey/hu/ {
        default_type "application/octet-stream";
        add_header Access-Control-Allow-Origin * always;
      }

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
