apiVersion: apps/v1
kind: Deployment
metadata:
  name: wkd
  labels:
    app: wkd
spec:
  template:
    spec:
      initContainers:
        - name: generator
          args:
            - "--use-folder"
            - "/data/keys/"
            - "--direct"
