apiVersion: apps/v1
kind: Deployment
metadata:
  name: wkd
spec:
  template:
    spec:
      containers:
        - name: generator
          args:
            - "--use-folder"
            - "/data/keys/"
            - "--advanced"
