apiVersion: apps/v1
kind: Deployment
metadata:
  name: wkd
  labels:
    app.kubernetes.io/name: wkd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wkd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wkd
    spec:
      serviceAccountName: wkd
      containers:
        - name: watcher
          image: "kiwigrid/k8s-sidecar:latest"
          env:
            - name: LABEL
              value: wkd
            - name: LABEL_VALUE
              value: 'enroll'
            - name: FOLDER
              value: /tmp/keys
          volumeMounts:
            - name: keys
              mountPath: /tmp/keys/
        - name: generator
          image: "drgrove/wkd:latest"
          env:
            - name: OUTPUT_FOLDER
              value: /data/output/
          volumeMounts:
            - name: keys
              mountPath: /data/keys/
            - name: wkd
              mountPath: /data/output/
          command:
            - /usr/local/bin/wkd-sync
          args:
            - "--use-folder"
            - "/data/keys/"
        - name: nginx
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: wkd
              mountPath: /usr/share/nginx/html/
            - name: nginx
              mountPath: /etc/nginx/conf.d/
      volumes:
      - name: wkd
        emptyDir: {}
      - name: keys
        emptyDir: {}
      - name: nginx
        configMap:
          name: nginx
