apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - nginx.cm.yaml
images:
  - name: drgrove/wkd
    newTag: v2.1.0
  - name: nginx
    newTag: 1.21.0
configMapGenerator:
  - name: keys
    files: []
