apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wkd
  labels:
    app.kubernetes.io/name: wkd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wkd
subjects:
- kind: ServiceAccount
  name: wkd
