apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: wkd
    app.kubernetes.io/part-of: wkd
  name: wkd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wkd
subjects:
- kind: ServiceAccount
  name: wkd
